### ISSUE TITLE
Case Study: Study the existing web pages of different colleges & universities

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#10]
Study webpage design patter. 
Study content priorities 
etc...

**Comment by Jenbati** [comment]
Collecting screenshot of those colleges & universities..

**Comment by Jenbati** [comment]
http://www.acme.edu.np/ 
http://www.thearyanschool.edu.np/
http://www.acmt.edu.np/
http://chbea.edu.np/
http://www.biomedical.edu.np/
http://www.cit.edu.np/
http://www.cjmc.edu.np/
http://www.hicast.edu.np/
https://www.hist.edu.np/
http://whitehouse.edu.np
http://www.nepalschoolofsocialwork.org/
http://kcc.edu.np/
http://www.kvc.com.np/
http://www.karnalicollege.edu.np/
http://www.kathtourism.edu.np/
http://www.kdbc.edu.np/
http://www.ksl.edu.np/
http://kist.edu.np/

**Comment by ErSKS** [comment]
@Jenbati Choose Best 3 websites among them.

**Comment by Jenbati** [comment]
Top 1: http://www.kdbc.edu.np/
Top 2: http://chbea.edu.np/
Top 3: http://whitehouse.edu.np/

**Comment by ErSKS** [comment]
What contents should we add to our website?
