### ISSUE TITLE
Make a complete solution of C - Programming [FINAL ASSESSMENT - 2074] computer engineering faculty. 

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#11]
**Q. 2b. Write the output of following program.** 
#include<stdio.h>
int main()
{
int x=10, y=1;
x= ++x + x++;
y=y++ + ++y;
printf("%d%d",x,y);
return 0;
}

**OUTPUT** 
23    5

**Comment by Jenbati** [comment]
Q. 2b. Write the output of the following program. 
#include<stdio.h>
{
int x=10,y=1;
x=++x + x++;
y=y++ + ++y;
printf("%d%d",x,y);
return 0;
}

**Comment by Jenbati** [comment]
**Q. 3b. WAP to display following pattern using unformatted output statement, ask user to enter n. n should be odd number otherwise re-ask user to enter n. The patter for n=5 is 
..........@
.....@@@
@@@@@
.....@@@
.........@**

#include<stdio.h>
#include<conio.h>
void main()
{
int i,j,n,c=0;
clrscr();
while(1)
{
printf("\nEnter the (odd) no. of rows to display \t");
scanf("%d",&n);

if(n%2!=0)
break;
}

for(i=1;i<n;i++)
{
if(i%2!=0)
c++;
}

n=n-c;

for(i=1;i<=n;i++)
{
   for(j=1;j<=n-i;j++)
   putchar(' ');

   for(j=1;j<=2*i-1;j++)
   putchar('@');

   putchar('\n');

}

for(i=n-1;i>=1;i--)
{
   for(j=1;j<=n-i;j++)
   putchar(' ');

   for(j=2*i-1;j>=1;j--)
   putchar('@');

   putchar('\n');

}
getch();
}

**OUTPUT**
Enter the (odd) no. of rows to display  7
.................@
.............@@@
.........@@@@@
.....@@@@@@@
.........@@@@@
.............@@@
.................@

**Comment by Jenbati** [comment]
**Q. 4. a. The monthly electricity bill is to be computed as follows: a. Minium Rs. 80/- for up to 20 units, b. Rs. 7.3 per unit for next 100 units, c) Rs. 9.0 per unit for any units beyond 120 units. WAP in C to compute monthly bill for given number of units consumed by a consumer. Electricity unit entered by a user should pass to a function calcAmount() & display bill amount from main using pointer concept. [4]**

#include<stdio.h>
#include<conio.h>
float calcAmount(float x);

void main()
{
float unit,result,*pu,*pr;
clrscr();
pu=&unit;
pr=&result;
printf("Enter the units\t");
scanf("%f",pu);
*pr=calcAmount(*pu);
printf("\n\nRequired monthly electricity bill is %f",*pr);
getch();
}

float calcAmount(float x)
{
float amount,*pa;
pa=&amount;

    if(x<=20)
    {
    *pa=80.0;
    }
    else if(x>20 && x<=120)
    {
    *pa=80.0+((x-20.0)*7.3);
    }
    else
    {
    *pa=80.0+730.0+((x-120.0)*9.0);
    }
return(*pa);
}

**OUTPUT**
Enter the units 180

Required monthy electricity bill is 1350.000000

**Comment by Jenbati** [comment]
**4b. WAP to calculate sum of digits of a given 5-digits number entered by the user using recursive function. [4]**

#include<stdio.h>
#include<conio.h>
int sumofdigits(int x);

void main()
{
int n,result;
clrscr();
printf("Enter any 5 digits number\t");
scanf("%d",&n);
result=sumofdigits(n);
printf("Requried sum is %d ",result);
getch();
}

int sumofdigits(int x)
{
static int sum=0;
  if(x<=0)
  {
  return(sum);
  }
  else
  {
  sum=sum+x%10;
  x=x/10;
  sumofdigits(x);
  }
}

**OUTPUT:** 
Enter any 5 digits number 12345
Required sum is 15

**Comment by Jenbati** [comment]
**5a. WAP to read 3x3 square matrix, find minimum integer value of a matrix, replace the diagonal elements by minimum element and display it using pointer. [6]**

#include<stdio.h>
#include<conio.h>
void main()
{
int a[3][3],i,j,small,*p;
clrscr();
p=&a[0][0];
printf("Enter any 9 no. for 3x3 matrix\n");
for(i=0;i<3;i++)
{
   for(j=0;j<3;j++)
   {
      scanf("%d",p+3*i+j);
   }
}

small=*p;

for(i=0;i<3;i++)
{
   for(j=0;j<3;j++)
   {
       if(*(p+3*i+j)<small)
       {
	small=*(p+3*i+j);
       }
   }
}

for(i=0;i<3;i++)
{
   for(j=0;j<3;j++)
   {
      if(i==j)
      {
       *(p+3*i+j)=small;
      }
   }
}

printf("\n\n Required matrix \n\n");
for(i=0;i<3;i++)
{
   for(j=0;j<3;j++)
   {
      printf("%d\t",*(p+3*i+j));
   }
   printf("\n");
}
getch();
}

**OUTPUT**
Enter any 9 no. for 3x3 matrix
5
7
9
1
3
4
6
8
2

Required matrix 
1.....7.....9
1.....1.....4
6.....8.....1

**Comment by Jenbati** [comment]
**5b. WAP to read 10 names of students and sort them alphabetically. The process must be done by the user defined function. [4]**

#include<stdio.h>
#include<conio.h>
#include<string.h>
#define S 10

void sorting(char a[S][20]);

void main()
{
char a[S][20];
int i,j;
clrscr();
printf("Enter the name of 10 students\n\n");
for(i=0;i<S;i++)
{
   scanf("%s",&a[i]);
}
sorting(a);

printf("\nAlphabetical order\n");
for(i=0;i<S;i++)
{
printf("%s\n",a[i]);
}

getch();
}

void sorting(char a[S][20])
{
int i,j;
char temp[20];

for(i=0;i<S;i++)
{
   for(j=0;j<S;j++)
   {
      if((strcmp(a[i],a[j]))<0)
      {
       strcpy(temp,a[i]);
       strcpy(a[i],a[j]);
       strcpy(a[j],temp);
      }
   }
}

}

**OUTPUT**
Enter the name of 10 students

sahas
rojash
prashun
oshin
nirjal
aayush
bikesh
kiran
lucky
dinesh

Alphabetical order
aayush
bikesh
dinesh
kiran
lucky
nirjal
oshin
prashun
rojash
sahas

**Comment by Jenbati** [comment]
**Q.6 b. WAP to read a string from user and use a user defined function to copy the contents of the read string into another character array changing lower case letter to upper if any. Use pointer to process the string.** 


#include<stdio.h>
#include<conio.h>

void string(char a[100]);

void main()
{
char a[100];
clrscr();
printf("Enter any string");
gets(a);
string(a);
getch();
}

void string(char a[100])
{
char b[100]={""};
char *pa,*pb;
int i;
for(i=0;  ;i++)
{
  pa=&a[i];
  pb=&b[i];
  if(*pa=='\0')
  break;

  if(*pa>=97 && *pa<=122)
  *pb=*pa-32;
  else
  *pb=*pa;
}

puts(b);
}

**OUTPUT**
Enter any stringHAPPY coding JEN!!!
HAPPY CODING JEN!!!

**Comment by Jenbati** [comment]
**Q.9.b. WAP in FORTRAN to test whether the accepted year is leap or not. [5]** 

![9b](https://user-images.githubusercontent.com/36839891/36944912-61184682-1fcd-11e8-9fd5-d498882669c4.png)

**OUTPUT**

![9b leap year](https://user-images.githubusercontent.com/36839891/36944916-685e009e-1fcd-11e8-9c98-97aa25687d84.png)

**Comment by Jenbati** [comment]
Remaining question will be completing later. 
**8 b. WAP that first appends records of five employees in a binary file and display the contents from file. The file name should be given by user and display message if it does not exit.**

**Comment by ErSKS** [comment]
Thank You !
