### ISSUE TITLE
Select reference theme for FrontEnd of BCT Khwopa

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#12]
Which theme you like most?

**Comment by Jenbati** [comment]
Found Charisma- Master Admin template for BACK-END DEVELOPMENT              
https://usman.it/themes/charisma/

**Comment by Jenbati** [comment]
http://cdn.livedemo00.template-help.com:82/wt_37828/#
Buy here: http://mytemplatesstore.com/catalog/template/37828

http://freetemplates.bz/design/site-theme/?theme=wieldstrem

http://www.templateaccess.com/demos/6052/

http://preview.themeforest.net/item/academy-learning-management-theme/full_screen_preview/4169073?ref=pnpress&clickthrough_id&redirect_back=true

**Comment by Jenbati** [comment]
https://chocotemplates.com/demo/?template=curve
https://previews.chocotemplates.com/simple/html/index.html
https://chocotemplates.com/demo/?template=retina

**Comment by ErSKS** [comment]
Yi 3 Otai bhanda ajhai ramro template hernu

**Comment by ErSKS** [comment]
**BackEnd** Sample Template: [Preview](https://startbootstrap.com/template-overviews/sb-admin-2/)/[Download](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/archive/gh-pages.zip)
