### ISSUE TITLE
Use Entry Controller

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#33]
- Assessment
- Attendance

**Comment by ErSKS** [comment]
The controller has been generated successfully.

**Comment by ErSKS** [comment]
Default Action: index redirects to entry/attendance

**Comment by Jenbati** [comment]
**Successfully tested using Sarita Mam username & Password**

![image](https://user-images.githubusercontent.com/36839891/37826768-e868fc96-2ebc-11e8-870a-07d07d9a5c0c.png)

![image](https://user-images.githubusercontent.com/36839891/37826626-46374c70-2ebc-11e8-881a-f54d75db52d2.png)

**Comment by Jenbati** [comment]
**Successfully tested using Migma Ma Username & password**
![image](https://user-images.githubusercontent.com/36839891/37827565-1ec9d3d4-2ec0-11e8-9153-8b0e0dceb93b.png)
![image](https://user-images.githubusercontent.com/36839891/37873386-a8de8c14-303b-11e8-9098-f5dd96046225.png)
Error in Batch

**Comment by Jenbati** [comment]
Migma mam re-checking... 

![image](https://user-images.githubusercontent.com/36839891/37873377-8252edc4-303b-11e8-9c89-c3ad48d912ac.png)
