### ISSUE TITLE
Prepare SubToLect Document

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#34]
Lect | Dept | Sem | Subject | Batch | ...

**Comment by Jenbati** [comment]
![image](https://user-images.githubusercontent.com/36839891/37826008-01830e2c-2eba-11e8-89bd-c5416fc7f662.png)

**Comment by Jenbati** [comment]
![image](https://user-images.githubusercontent.com/36839891/37826042-3031aaa8-2eba-11e8-91cc-92a1fc6f3c7e.png)
