### ISSUE TITLE
Assign Course to New Students

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#35]
Use Bulk Course Assign Module

**Comment by Jenbati** [comment]
courseassign/select_student
**2073/2016 Batch**

BE Computer Faculty (Code - 03)
730301 - 730351 Completed

BE Electronics & Communication Faculty (Code - 04)
730401 - 730427 Completed

BE Civil Faculty (Code - 02)
730201 - 730296 Completed

BE Architecture (Code - 01)
730101 - 730149 Completed

**Comment by Jenbati** [comment]
courseassign/select_student
**2074/2017 Batch**

BE Computer Faculty (Code - 03)
740301 - 740351 Completed   

BE Electronics & Communication Faculty (Code - 04)
740401 - 740427 Completed

BE Civil Faculty (Code - 02)
740201 - 740296 Completed

BE Architecture (Code - 01)
740101 - 740149 Completed

**Comment by Jenbati** [comment]
courseassign/select_student
**2072/2015 Batch**

BE Electronics & Communication Faculty (Code - 04)
720401 - 720426
