### ISSUE TITLE
Find no. of pages of khec.edu.np

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#4]
Use various online tools

**Comment by Jenbati** [comment]
HOME 
Home page:       http://khec.edu.np/       
About us:          http://khec.edu.np/site/aboutus.html

ENTRANCE
Entrance page:                http://khec.edu.np/entrance/index.html
Entrance information:      http://khec.edu.np/entrance/content/401.html
Entrance notice:               http://khec.edu.np/entrance/notice/3004.html
1st merit list:                   http://khec.edu.np/entrance/notice/3003.html
2nd merit list:                  http://khec.edu.np/entrance/notice/3004.html
Admission requirement:   http://khec.edu.np/entrance/content/402.html
Scholarship:                     http://khec.edu.np/entrance/content/403.html
Program offered:             http://khec.edu.np/entrance/content/501.html
College features:              http://khec.edu.np/entrance/content/502.html
Photo Gallery:                 http://khec.edu.np/entrance/photo_gallery.html
FAQ:                               http://khec.edu.np/entrance/faq/39.html

STUDY WITH US
Courses: 
ME in Earthquake:                                 http://khec.edu.np/course/view/?dept_id=6.html 
MSC in Urban Design & Conservation:  http://khec.edu.np/course/view/?dept_id=7.html
Bachelor in Architecture:                        http://khec.edu.np/course/view/?dept_id=1.html

**Comment by ErSKS** [comment]
There are other 500+ Pages which you don't list here.
