### ISSUE TITLE
Keep displaying NQ student list in a particular subject

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#42]
**Suggested by 
Computer department (Reena mam)
Science & Humanities department
Architecture department**

**Comment by ErSKS** [comment]
Give Admin Access of Internal Marks to HoDs:
![2018-03-29_143743](https://user-images.githubusercontent.com/5508421/38079571-f6ea5fb6-335e-11e8-91a8-30900bc260b6.jpg)

**Comment by ErSKS** [comment]
Enable this icon:
![2018-03-29_152832](https://user-images.githubusercontent.com/5508421/38082284-e3165db2-3365-11e8-8043-a4f45defe315.jpg)
