### ISSUE TITLE
Separate Group A/B and C/D Civil Faculty

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#43]
Suggested by Reena mam. 
As Group A/B is taught by one teacher (Reena mam) and Group C/D is taught by another teacher. 
There is delay in submission of marks due to delay made by another teacher.

**Comment by ErSKS** [comment]
Tell her to inform his co-lecturer by messaging or making call. 
Transfer "Send to Exam" responsibility to co-person who makes delay to submit.
