### ISSUE TITLE
Change pass marks 32 to 16 in the following subject

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#51]
Found error while generating error in the following subjects. 
Semester I Building Material-I 
Semester I Building Construction-I
Semester I Introduction to architecture

![image](https://user-images.githubusercontent.com/36839891/38182962-a90d7c5a-365c-11e8-9908-b1226595ccef.png)

**Comment by ErSKS** [comment]
Red label removed !
