### ISSUE TITLE
Reset Gajendra's sir college web-mail password

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#61]
![reset](https://user-images.githubusercontent.com/36839891/38467726-4e535b36-3b5c-11e8-8710-ff3685304c7c.jpg)

**Comment by ErSKS** [comment]
Upload latest photo

**Comment by Jenbati** [comment]
**Task Accomplished** 

![image](https://user-images.githubusercontent.com/36839891/38539609-9c55ba10-3cb8-11e8-86cf-26cc6a4a538b.png)

**Comment by ErSKS** [comment]
Reset !
