### ISSUE TITLE
Create MIS Account for 663 Students

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#64]
For 2072/73/74 Batch Students

**Comment by Jenbati** [comment]
Created Username & Password using http://192.168.*.*/mis.php/user/import

Civil 2015 (2072) Batch All
Computer 2015 (2072) Batch All
Electronics & Communication 2015 (2072) Batch All

Architecture 2016 (2073) Batch All
Civil 2016 (2073) Batch All
Computer 2016 (2073) Batch All
Electronics & Communication 2016 (2073) All

Architecture 2017 (2014) Batch All
Civil 2017 (2074) Batch All
Computer 2017 (2074) Batch All
Electronics & Communication 2017 (2074) Batch All
