### ISSUE TITLE
Necessity of hiding internal marks of following internal subjects 

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#65]
Necessity of hiding internal marks from students point of view.

**Comment by Jenbati** [comment]
**Electronics and Communication**
Project-I (VII-Semester) (Code-218)
Project-II (VIII-Semester) (Code-233)

**Comment by Jenbati** [comment]
**Civil**
Survey Camp (V-Semester) (Code-93)
Project (VIII-Semester) (Code-116)

**Comment by Jenbati** [comment]
**Architecture**
Design Studio-III (III-Semester) (Code - 21)
Design Studio-V (V-Semester) (Code - 35)
Design Studio-VII (VII-Semester) (Code - 51)
Design Studio-VIII (VIII-Semester) (Code - 60)

**Comment by Jenbati** [comment]
**Computer Faculty**
Project-I (III-Semester) (Code - 143)
Project-II (V-Semester) (Code - 154)
Project-III (VII-Semester) (Code - 166)
Project-IV (VIII-Semester) (Code - 174)

**Comment by ErSKS** [comment]
![hidden](https://user-images.githubusercontent.com/5508421/38918092-63854872-430c-11e8-9d79-add8a5c73888.PNG)

**Comment by ErSKS** [comment]
- Just try to write a logic for that page.
- Display blank if the course name looks like %project%.
