### ISSUE TITLE
Setup MIS Computer/Printer @BCT, KhCE

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#7]

**Comment by Jenbati** [comment]
Shifted 1 monitor, 2 CPU, 1 UPS, 1 mouse, 1 keyboard, speaker, printer & its cable from MIS section department to Computer Engineering department TU.

**Comment by ErSKS** [comment]
Reference Page: http://khwopa.edu.np/computer/index.html

**Comment by Jenbati** [comment]
Shifted MIS movable chair @ BCT, KhCE
