### ISSUE TITLE
College webmail for following Civil Department Lecturer

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#71]
New college webmail for following lecturer

![2](https://user-images.githubusercontent.com/36839891/39977953-3e4b6b12-575d-11e8-9e16-cd6db3917b8c.jpg)
![1](https://user-images.githubusercontent.com/36839891/39977954-3e7d0532-575d-11e8-85a0-27e5d67db643.jpg)

**Comment by Jenbati** [comment]
Resetting password for following lecturer

![1](https://user-images.githubusercontent.com/36839891/39977999-8b948ffc-575d-11e8-9ba2-965c6450da56.jpg)
![2](https://user-images.githubusercontent.com/36839891/39978000-8bc3ac24-575d-11e8-829d-eb62c6fa9f55.jpg)

**Comment by ErSKS** [comment]
2 Emails created & password of 2 emails were reset.
