### ISSUE TITLE
Design Webpage for Computer Department, KhCE (TU)

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhEC#8]

**Comment by ErSKS** [comment]
Reference Page: http://khwopa.edu.np/computer/index.html

**Comment by Jenbati** [comment]
![2](https://user-images.githubusercontent.com/36839891/37019892-15055dea-2142-11e8-8031-2279fdc78132.jpg)

**Comment by Jenbati** [comment]
![1](https://user-images.githubusercontent.com/36839891/37019900-1d0ed7c8-2142-11e8-858b-895d7ef54a4a.jpg)

**Comment by Jenbati** [comment]
![2](https://user-images.githubusercontent.com/36839891/37019920-2f5fe890-2142-11e8-9808-dc031a284580.jpg)

**Comment by ErSKS** [comment]
Implement in New HTML5 Responsive Design

**Comment by Jenbati** [comment]
![fireshot capture 1](https://user-images.githubusercontent.com/36839891/37396426-f6b349d2-27a0-11e8-9234-4cef9039c908.png)

**Comment by Jenbati** [comment]
![image](https://user-images.githubusercontent.com/36839891/37396470-13b6eb1a-27a1-11e8-80b9-a38fd71f60c3.png)
