### ISSUE TITLE
Complete Mini-Project#1

### ISSUE THREAD

**Issue by ErSKS** [KhwopaMIS/KhEC#9]
https://github.com/KhwopaMIS/KhEC/projects/1

**Comment by Jenbati** [comment]
![fireshot capture 1 -](https://user-images.githubusercontent.com/36839891/37019807-ccadd680-2141-11e8-83bf-186097e8ecd5.png)

**Comment by Jenbati** [comment]
![fireshot capture 4 - curve - free css templat_ - file____c__users_jen_desktop_html_default_home html](https://user-images.githubusercontent.com/36839891/37019959-4c02409c-2142-11e8-8337-886862949ef2.png)
